---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        kamailio_version: "{{ lookup('env', 'KAMAILIO_VERSION') }}"
        kamailio_config_file_content: "{{ lookup('template', 'kamailio.cfg.j2') }}"


    - name: Install prerequisites
      block:
        - name: Update apt cache
          when: ansible_os_family == "Debian"
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false

        - package:
            name: "{{ item }}"
            state: present
          with_items: 
            - rsyslog

  roles:
    - role: ansible-role-kamailio
      tags:
        - kamailio
